---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cicd-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-cicd-k8s-app
      version: blue
  template:
    metadata:
      name: demo-cicd-k8s-pod
      labels:
        app: demo-cicd-k8s-app
        version: blue
    spec:
      serviceAccountName: k8s-101-role
      containers:
      - name: demo-cicd-k8s-container
        image: 192.168.1.39:5000/demo-cicd-k8s-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: regcred    
---
apiVersion: v1
kind: Service 
metadata:
  name: demo-cicd-k8s-svc
  labels:
    app: demo-cicd-k8s-app
spec:
  selector:
    app: demo-cicd-k8s-app
    version: blue
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8090
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-101-role
subjects:
- kind: ServiceAccount
  name: k8s-101-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-101-role