---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitlab-admin
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cicd-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-cicd-k8s-app
      version: blue
  template:
    metadata:
      name: demo-cicd-k8s-pod
      labels:
        app: demo-cicd-k8s-app
        version: blue
    spec:
      containers:
      - name: demo-cicd-k8s-container
        image: 192.168.1.39:5000/demo-cicd-k8s-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: regcred    
---
apiVersion: v1
kind: Service 
metadata:
  name: demo-cicd-k8s-svc
  labels:
    app: demo-cicd-k8s-app
spec:
  selector:
    app: demo-cicd-k8s-app
    version: blue
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8090
